name: _build

env:
  SLNNAME: Smoerfugl._build.sln
  SLNPATH: _build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - run: |
          dotnet restore ${{ env.SLNNAME }}
          dotnet build --configuration Release --no-restore ${{ env.SLNNAME }}
          dotnet test --no-restore --verbosity normal ${{ env.SLNNAME }} --logger "trx;LogFileName=/tmp/testresults.trx"
        working-directory: ${{ env.SLNPATH }}
      
      - name: Tests
        if: ${{ !cancelled() }}
        uses: zyborg/dotnet-tests-report@v1
        with:
          test_results_path: /tmp/testresults.trx
          report_name: Tests
          report_title: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: /tmp
