name: _build

env:
  SLNNAME: Smoerfugl._build.sln
  SLNPATH: _build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - run: |
          dotnet-gitversion /updateprojectfiles

          dotnet restore ${{ env.SLNNAME }}
          dotnet build --configuration Release --no-restore ${{ env.SLNNAME }}
          mkdir -p ${{ github.workspace }}/TestResults
          dotnet test --no-restore --logger trx --results-directory /tmp/TestResults ${{ env.SLNNAME }}
        working-directory: ${{ env.SLNPATH }}

      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        id: trx-parser
        with:
          name: Test report
          path: /tmp/TestResults/*.trx
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: /tmp/TestResults

      - name: Publish
        run: dotnet pack ${{ env.slnName }} -c Release --no-build -o /tmp/nuget/ -p:PackageVersion=${{ steps.gitversion.outputs.SemVer }}
        working-directory: ${{ env.slnPath }}

      - name: Upload .pkg artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: /tmp/nuget
  
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Download nuget artifact
        uses: actions/download-artifact@v1
        with:
          name: nuget

      - name: Push to nuget.org
        run: |
          dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_ORG_APIKEY }} -s https://api.nuget.org/v3/index.json