name: _build

env:
  SLNNAME: Smoerfugl._build.sln
  SLNPATH: _build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - run: |
          dotnet restore ${{ env.SLNNAME }}
          dotnet build --configuration Release --no-restore ${{ env.SLNNAME }}
          mkdir -p ${{ github.workspace}/TestResults
          dotnet test --no-restore --verbosity normal --logger trx --results-directory ${{ github.workspace }}/TestResults ${{ env.SLNNAME }}
        working-directory: ${{ env.SLNPATH }}
      
      # Using the trx-parser action
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.1
        id: trx-parser
        with:
          TRX_PATH: ${{ github.workspace }}/TestResults #This should be the path to your TRX files
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ github.workspace }}/TestResults
