name: _build

env:
  SLNNAME: Smoerfugl._build.sln
  SLNPATH: _build
  TEST_OUTPUT_DIR: _build/test_output
  TEST_OUTPUT_FILE: _build/test_output/test_results.trx
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - run: |
          dotnet restore ${{ env.SLNNAME }}
          dotnet build --configuration Release --no-restore ${{ env.SLNNAME }}
          mkdir ~/tmp
          dotnet test --no-restore --verbosity normal ${{ env.SLNNAME }} --logger "trx;LogFileName=${TEST_OUTPUT_FILE}"
        working-directory: ${{ env.SLNPATH }}
      
      - name: Tests
        if: ${{ !cancelled() }}
        uses: zyborg/dotnet-tests-report@v1
        with:
          test_results_path: _build/test_output
          report_name: Tests
          report_title: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: _build/test_output
